# Generated by Django 5.2.1 on 2025-07-18 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('central_lambda', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Bands',
                'db_table': 'Band',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Instruments',
                'db_table': 'Instrument',
            },
        ),
        migrations.CreateModel(
            name='Lvl2CalStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Lvl2 Cal Statuses',
                'db_table': 'Lvl2Cal_Status',
            },
        ),
        migrations.CreateModel(
            name='Lvl3DiffStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Lvl3 Diff Statuses',
                'db_table': 'Lvl3Diff_Status',
            },
        ),
        migrations.CreateModel(
            name='Lvl3MosaicStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Lvl3 Mosaic Statuses',
                'db_table': 'Lvl3Mosaic_Status',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Epoch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('start_mjd', models.FloatField(null=True)),
                ('end_mjd', models.FloatField(null=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffpype.band')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffpype.project')),
            ],
            options={
                'verbose_name_plural': 'Epochs',
                'db_table': 'Epoch',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ra', models.FloatField()),
                ('decl', models.FloatField()),
                ('obs_start', models.DateTimeField()),
                ('mjd_avg', models.FloatField(null=True)),
                ('exp_time', models.FloatField()),
                ('target_name', models.CharField(max_length=128)),
                ('base_filename', models.CharField(max_length=255, unique=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffpype.band')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffpype.instrument')),
            ],
            options={
                'verbose_name_plural': 'Images',
                'db_table': 'Image',
            },
        ),
        migrations.CreateModel(
            name='Lvl2Cal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_file_ext', models.CharField(max_length=128)),
                ('poly', models.TextField(blank=True, null=True)),
                ('plate_scale', models.FloatField()),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diffpype.image')),
                ('lvl2cal_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffpype.lvl2calstatus')),
            ],
            options={
                'verbose_name_plural': 'Lvl2 Cals',
                'db_table': 'Lvl2Cal',
            },
        ),
        migrations.CreateModel(
            name='Lvl2Cal_Epoch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('epoch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffpype.epoch')),
                ('lvl2cal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffpype.lvl2cal')),
            ],
            options={
                'verbose_name_plural': 'Lvl2 Cals in Epoch',
                'db_table': 'Lvl2Cal_Epoch',
            },
        ),
        migrations.CreateModel(
            name='Lvl3Mosaic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_plate_scale', models.FloatField()),
                ('filename', models.CharField(max_length=128, unique=True)),
                ('poly', models.TextField(blank=True, null=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffpype.band')),
                ('epoch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffpype.epoch')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffpype.instrument')),
                ('lvl3mosaic_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffpype.lvl3mosaicstatus')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffpype.project')),
            ],
            options={
                'verbose_name_plural': 'Lvl3 Mosaics',
                'db_table': 'Lvl3Mosaic',
            },
        ),
        migrations.CreateModel(
            name='Lvl3Diff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=128)),
                ('lvl3diff_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffpype.lvl3diffstatus')),
                ('lvl3_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diff_as_reference', to='diffpype.lvl3mosaic')),
                ('lvl3_sci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diff_as_science', to='diffpype.lvl3mosaic')),
            ],
            options={
                'verbose_name_plural': 'Lvl3 Diffs',
                'db_table': 'Lvl3Diff',
            },
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('ra', models.FloatField()),
                ('decl', models.FloatField()),
                ('delta_ra', models.FloatField()),
                ('delta_decl', models.FloatField()),
                ('coord_sys', models.IntegerField()),
                ('poly', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffpype.project')),
            ],
            options={
                'verbose_name_plural': 'Tiles',
                'db_table': 'Tile',
            },
        ),
        migrations.AddField(
            model_name='lvl3mosaic',
            name='tile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffpype.tile'),
        ),
        migrations.AddField(
            model_name='epoch',
            name='tile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffpype.tile'),
        ),
        migrations.CreateModel(
            name='TileLvl2Cal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lvl2cal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffpype.lvl2cal')),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffpype.tile')),
            ],
            options={
                'verbose_name_plural': 'Tile - Lvl2 Cals',
                'db_table': 'Tile_Lvl2Cal',
            },
        ),
        migrations.AlterUniqueTogether(
            name='lvl3mosaic',
            unique_together={('instrument', 'tile', 'epoch', 'band', 'project')},
        ),
    ]
