# Generated by Django 5.2.1 on 2025-07-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diffpype', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lvl3mosaic',
            old_name='poly',
            new_name='moc_str',
        ),
    ]
