"""add project slug (with backfill) and ingest_batches

Revision ID: 0009
Revises: 0008
Create Date: 2026-07-27

Adds an immutable, unique `slug` column to `projects` (generated via
python-slugify at creation time, rejecting collisions with an HTTP 400 —
see src/services/project_service.py) and creates the `ingest_batches`
table that tracks the progress of an async ingest run (doc 28).

Hand-authored, not autogenerated: the `slug` column needs a data backfill
step for any pre-existing Project rows, which autogenerate cannot produce.
The column is added nullable first, backfilled by slugifying each row's
`name` and auto-deduplicating collisions with a numeric suffix (-2, -3,
...), and only then altered to NOT NULL. Auto-dedupe (rather than the
interactive-rejection behavior used for new project creation) is used here
because there is no user to reject a collision against mid-migration.
"""

import sqlalchemy as sa
from alembic import op
from slugify import slugify
from sqlalchemy.dialects import postgresql

revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None


def _job_status_enum() -> postgresql.ENUM:
    """Reference the job_status enum type created in migration 0001 (never re-create it)."""
    return postgresql.ENUM(
        "pending",
        "in_process",
        "complete",
        "failed",
        name="job_status",
        create_type=False,
    )


def _unique_slug(base_slug: str, taken: set[str]) -> str:
    """Return base_slug, or base_slug-2/base_slug-3/... the first value not already in `taken`."""
    if base_slug not in taken:
        return base_slug
    suffix = 2
    candidate = f"{base_slug}-{suffix}"
    while candidate in taken:
        suffix += 1
        candidate = f"{base_slug}-{suffix}"
    return candidate


def upgrade() -> None:
    # --- projects.slug: add nullable, backfill, then enforce NOT NULL + unique ---
    op.add_column("projects", sa.Column("slug", sa.String(), nullable=True))

    bind = op.get_bind()
    projects = sa.table(
        "projects",
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
        sa.column("slug", sa.String),
    )
    existing_rows = bind.execute(sa.select(projects.c.id, projects.c.name)).fetchall()

    taken_slugs: set[str] = set()
    for row in existing_rows:
        slug = _unique_slug(slugify(row.name), taken_slugs)
        taken_slugs.add(slug)
        bind.execute(projects.update().where(projects.c.id == row.id).values(slug=slug))

    op.alter_column("projects", "slug", nullable=False)
    op.create_unique_constraint("uq_project_slug", "projects", ["slug"])

    # --- ingest_batches: async ingest progress tracking ---
    op.create_table(
        "ingest_batches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("s3_prefix", sa.String(), nullable=False),
        sa.Column("total_files", sa.Integer(), nullable=False),
        sa.Column("processed_files", sa.Integer(), nullable=False),
        sa.Column("status", _job_status_enum(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    op.drop_table("ingest_batches")
    op.drop_constraint("uq_project_slug", "projects", type_="unique")
    op.drop_column("projects", "slug")
