"""add native point-HEALPix range columns, GiST indexes, and IngestBatch job FK

Revision ID: 0011
Revises: 0010
Create Date: 2026-07-28

Doc 29 §2 (resolves issue #26). Migrates Tile.healpix_index from a single
fixed-NSIDE Integer to a native depth-29 INT8RANGE (PointHEALPixType), and adds
the same point-index column to every other model that owns its own ra/decl
(Level2Image, Level3Mosaic), so cross-table containment against a footprint
becomes an indexed ``footprint @> healpix_index`` (``int8multirange @>
int8range``) operation. Also adds IngestBatch.job_configuration_id to bring it
to parity with Level3Mosaic (consumed by doc 30's per-job staleness overrides).

Hand-authored, not autogenerated: Postgres cannot cast ``int -> int8range``, so
Tile.healpix_index is dropped and recreated rather than altered in place. The
column was never written by any code path (always NULL), so no data is lost.
Empty-table assumption for the NOT NULL adds: every path that runs this
migration — CI, the pytest session (conftest builds base->head on a fresh
schema), and a dev-DB reset — applies it to a freshly built schema with no rows.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0011"
down_revision = "0010"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Tile.healpix_index: Integer -> INT8RANGE (NOT NULL). Drop + recreate.
    op.drop_column("tiles", "healpix_index")
    op.add_column(
        "tiles",
        sa.Column("healpix_index", postgresql.INT8RANGE(), nullable=False),
    )
    op.create_index(
        "ix_tile_healpix_index_gist",
        "tiles",
        ["healpix_index"],
        postgresql_using="gist",
    )

    # Level2Image.healpix_index: new NOT NULL point index (ra/decl always present).
    op.add_column(
        "level2_images",
        sa.Column("healpix_index", postgresql.INT8RANGE(), nullable=False),
    )
    op.create_index(
        "ix_level2_image_healpix_index_gist",
        "level2_images",
        ["healpix_index"],
        postgresql_using="gist",
    )

    # Level3Mosaic.healpix_index: nullable, mirrors its nullable ra/decl barycenter.
    op.add_column(
        "level3_mosaics",
        sa.Column("healpix_index", postgresql.INT8RANGE(), nullable=True),
    )
    op.create_index(
        "ix_level3_mosaic_healpix_index_gist",
        "level3_mosaics",
        ["healpix_index"],
        postgresql_using="gist",
    )

    # IngestBatch.job_configuration_id: parity with Level3Mosaic's existing FK.
    op.add_column(
        "ingest_batches",
        sa.Column("job_configuration_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        "fk_ingest_batches_job_configuration_id_job_configurations",
        "ingest_batches",
        "job_configurations",
        ["job_configuration_id"],
        ["id"],
    )


def downgrade() -> None:
    op.drop_constraint(
        "fk_ingest_batches_job_configuration_id_job_configurations",
        "ingest_batches",
        type_="foreignkey",
    )
    op.drop_column("ingest_batches", "job_configuration_id")

    op.drop_index("ix_level3_mosaic_healpix_index_gist", table_name="level3_mosaics")
    op.drop_column("level3_mosaics", "healpix_index")

    op.drop_index("ix_level2_image_healpix_index_gist", table_name="level2_images")
    op.drop_column("level2_images", "healpix_index")

    op.drop_index("ix_tile_healpix_index_gist", table_name="tiles")
    op.drop_column("tiles", "healpix_index")
    # Restore the original fixed-NSIDE integer column (nullable, as it was).
    op.add_column(
        "tiles",
        sa.Column("healpix_index", sa.Integer(), nullable=True),
    )
